---
# tasks file for conch_db

- name: Install Postgres 9.6
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql96
    - postgresql96-contrib

- name: Enable and start Postgres
  service:
    name: postgresql
    enabled: yes
    state: started

- name: Add postgres configuration
  copy:
    src: postgresql.conf
    dest: /var/pgsql/data/postgresql.conf
  notify:
    - restart postgres

- name: Add postgres HBA configuration
  copy:
    src: pg_hba.conf
    dest: /var/pgsql/data/pg_hba.conf
  notify:
    - restart postgres

- name: Install PsycoPG2 for postgresql_* tasks
  package:
    name: py27-psycopg2
    state: present

- name: Create conch login
  postgresql_user:
    name: conch
    password: "{{ conch_db_password}}"
    login_user: postgres
    login_password: postgres
    state: present

- name: Create conch database
  postgresql_db:
    name: conch
    owner: conch
    login_user: postgres
    login_password: postgres
    state: present

- name: Install postgres extensions
  postgresql_ext:
    name: "{{ item }}"
    db: conch
    login_user: postgres
    login_password: postgres
    state: present
  with_items:
    - pgcrypto
    - uuid-ossp

- name: Run migrations and build schema
  shell: /opt/conch/sql/run_migrations.sh
  environment:
    PGPASSWORD: "{{ conch_db_password }}"
  tags:
    - deploy
